# Generated by Django 5.0.7 on 2024-08-06 14:10

import django.db.models.deletion
import loanApp.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/default_profile_picture.png', upload_to=loanApp.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='employment_history',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('loan_application_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loan_type', models.CharField(choices=[(loanApp.models.LoanType['PERSONAL'], 'Personal'), (loanApp.models.LoanType['MORTGAGE'], 'Mortgage')], default=loanApp.models.LoanType['PERSONAL'], max_length=20)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=3)),
                ('loan_term', models.PositiveIntegerField()),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[(loanApp.models.Status['PENDING'], 'Pending'), (loanApp.models.Status['APPROVED'], 'Approved'), (loanApp.models.Status['REJECTED'], 'Rejected')], default=loanApp.models.Status['PENDING'], max_length=20)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loanApp.borrower')),
            ],
        ),
    ]
