# Generated by Django 5.0.7 on 2024-08-07 13:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0002_borrower_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='borrower_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0.05, max_digits=3),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='loan_type',
            field=models.CharField(choices=[('PERSONAL', 'Personal Loan'), ('MORTGAGE', 'Mortgage')], default='PERSONAL', max_length=10),
        ),
    ]
